<!DOCTYPE html>
<!--[if IE 7]> <html lang="en" class="ie7"> <![endif]-->  
<!--[if IE 8]> <html lang="en" class="ie8"> <![endif]-->  
<!--[if IE 9]> <html lang="en" class="ie9"> <![endif]-->  
<!--[if !IE]><!--> <html lang="en"> <!--<![endif]-->  
<head>
    <title>calcium-carbonate</title>

    <!-- Meta -->
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="description" content="" />
    <meta name="author" content="" />

    <!-- CSS Global Compulsory-->
    <link rel="stylesheet" href="assets/plugins/bootstrap/css/bootstrap.min.css" />
    <link rel="stylesheet" href="assets/css/style.css" />
    <link rel="stylesheet" href="assets/css/headers/header1.css" />
    <link rel="stylesheet" href="assets/plugins/bootstrap/css/bootstrap-responsive.min.css" />
    <link rel="stylesheet" href="assets/css/style_responsive.css" />
    <link rel="shortcut icon" href="favicon.ico" />        
    <!-- CSS Implementing Plugins -->    
    <link rel="stylesheet" href="assets/plugins/font-awesome/css/font-awesome.css" />
    <link rel="stylesheet" href="assets/plugins/bxslider/jquery.bxslider.css" />        
    <!-- CSS Theme -->    
    <link rel="stylesheet" href="assets/css/themes/default.css" id="style_color" />
    <link rel="stylesheet" href="assets/css/themes/headers/default.css" id="style_color-header-1" />    
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" /></head> 

<body>
 

<?php include 'header.php';?>

<!--=== Breadcrumbs ===-->
<div class="breadcrumbs margin-bottom-40">
	<div class="container">
        <h1 class="color-green pull-left">calcium-carbonate</h1>
        <ul class="pull-right breadcrumb">
            <li><a href="index.html">Home</a> <span class="divider">/</span></li>
            <li><a href="Ores-and-Minerals.html">Ores-and-Minerals</a> <span class="divider">/</span></li>
            <li class="active">calcium-carbonate</li>
        </ul>
    </div><!--/container-->
</div><!--/breadcrumbs-->
<!--=== End Breadcrumbs ===-->

<!--=== Content Part ===-->
<div class="container portfolio-item"> 	
	<div class="row-fluid margin-bottom-20"> 
		<!-- Carousel -->
        
        	<h3>Introduction of Calcium Carbonate</h3>
            <p>
Calcium carbonate is a kind of inorganic compounds, commonly known as grey stone, limestone, marble, etc. Its chemical formula is CaCO3, PH value neutral, insoluble in water, soluble in hydrochloric acid. Calcium carbonate is a type of common mineral substance on earth, exists in aragonite, calcite, chalk, limestone, marble, travertine and other rocks, also is the main component of the animal bones or shell. Calcium carbonate is generated by the combination of calcium ions and carbonate ions, so it is calcium+carbonate. Calcium carbonate is divided into two types: heavy calcium carbonate and light calcium carbonate. Due to the heavy calcium carbonate and precipitated calcium carbonate’s different nature of particle size, crystal and interface, the features of reaction is also vastly different. To this end, it extends many different varieties and different uses of calcium carbonate species, such as the activity of calcium carbonate, calcium carbonate for paper making, calcium carbonate for plastics, nanometer calcium carbonate, consumption of calcium carbonate, medicinal calcium carbonate, chemical calcium carbonate, coating calcium carbonate and so on.
        	<h3>Technological Process of Calcium Carbonate</h3>
            <p>
After being screened to remove gangue, raw materials will be delivered into stone crusher for coarse crushing, then to grinding mill for fine grinding to get micro calcium carbonate powder., finish through classifier for grading. The parts of powder which particle size conformed to the requirements will been packaged and warehoused as final products; other part do not conform to the specifications will be returned to calcium carbonate powder mill for grinding again. A complete set of calcium carbonate powder grinding machine is mainly composed of mill host, classifier, blower fan, jaw crusher, winnowing pan hoist, electromagnetic vibrating feeder, storage silo bin, bag-type dust collector, pipe device, cyclone powder machine, electric control cabinet, motor, etc. Calcium carbonate grinder machine is of vertical structure, cover area small, and host transmission device adopts enclosed gear box, smooth transmission. The mill adopts centralized control electrical system, advanced and reasonable shape, high degree of automation; vibrating feeder with small volume and light weight, easy to adjust and save electricity.
			</p>			
        	<h3>Application Fields of Calcium Carbonate</h3>
            <p>
Calcium carbonate is often used in construction industry and paper industry, as additive in food industry. Calcium carbonate within 200 mesh can be used for various feed supplement that calcium content of more than 55.6% without harmful ingredients. 250 mesh to 300 mesh calcium carbonate used as raw materials for plastics factory, rubber factory, paint, waterproof materials plant and exterior paint for building, whiteness more than 85 degrees. 400 mesh to 600 mesh calcium carbonate paste can be used in toothpaste, soap, white degree above 94 degrees. 800 mesh calcium carbonate is used in rubber, plastic, cable, PVC, white degree above 94 degrees. 1250 mesh calcium carbonate can be used in PVC, PE, paint, coating products, paper coating, paper surface coating, white degree above 95 degrees, with characteristics of high purity, high whiteness, non-toxic, odourless, low oil, low hardness, etc..		</p>	
        
		
    </div><!--/row-fluid-->

	


	
	
	
	
	
	
	
	

	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	<?php include 'porpularProduct.php';?>
	<!-- //End Recent Works -->                
</div><!--/container-->	 	
<!--=== End Content Part ===-->

	<?php include 'footer.php';?>

<!-- JS Global Compulsory -->           
<script type="text/javascript" src="assets/js/jquery-1.8.2.min.js"></script>
<script type="text/javascript" src="assets/js/modernizr.custom.js"></script>        
<script type="text/javascript" src="assets/plugins/bootstrap/js/bootstrap.min.js"></script> 
<!-- JS Implementing Plugins -->           
<script type="text/javascript" src="assets/plugins/bxslider/jquery.bxslider.js"></script>
<script type="text/javascript" src="assets/plugins/back-to-top.js"></script>
<!-- JS Page Level -->           
<script type="text/javascript" src="assets/js/app.js"></script>
<script type="text/javascript">
    jQuery(document).ready(function() {
        App.init();
        App.initBxSlider1();
    });
</script>
<!--[if lt IE 9]>
    <script src="assets/js/respond.js"></script>
<![endif]-->

</body>
</html> 